version: "3.8"
services:
    db:
        container_name: search-api-DB
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    backend:
        container_name: search-api-backend
        build: ./backend
        ports:
            - 3001:3001
        dns:
            - 8.8.8.8
    api:
        container_name: search-api-frontend
        build: ./frontend
        depends_on:
            - db
            - backend
        ports:
            - 3000:80
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: companies
        volumes:
            - "./frontend:/src"
volumes:
    db:
        driver: local
